project_id = "vuuesqrdjuqnduhiihwz"

[functions.razorpay-create-order]
verify_jwt = true

[functions.razorpay-webhook]
verify_jwt = false

[functions.razorpay-verify-payment]
verify_jwt = true

[functions.zinipay-create-invoice]
verify_jwt = true

[functions.zinipay-webhook]
verify_jwt = false

[functions.zinipay-verify-payment]
verify_jwt = true

[functions.send-email-otp]
verify_jwt = false

[functions.verify-email-otp]
verify_jwt = false